name: 'Slack Notification Action'
description: 'A GitHub Action to send Slack notifications about PR builds'
author: 'Your Name'

inputs:
  # Define any inputs if needed; you can use defaults
  pr_author:
    description: 'Author of the Pull Request'
    required: true
  repo:
    description: 'Repository name'
    required: true
  commit:
    description: 'Commit SHA'
    required: true
  message:
    description: 'Commit message'
    required: true
  status:
    description: 'Job status'
    required: true
  workflow:
    description: 'Workflow name'
    required: true
  job_name:
    description: 'Job name'
    required: true

secrets:
  slack_mapping:
    description: 'JSON Slack mapping of PR author to Slack user'
  slack_oauth_token:
    description: 'Slack OAuth token'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PR_AUTHOR: ${{ inputs.pr_author }}
    REPO: ${{ inputs.repo }}
    COMMIT: ${{ inputs.commit }}
    MESSAGE: ${{ inputs.message }}
    STATUS: ${{ inputs.status }}
    WORKFLOW: ${{ inputs.workflow }}
    JOB_NAME: ${{ inputs.job_name }}
    SLACK_MAPPING: ${{ secrets.slack_mapping }}
    SLACK_OAUTH_TOKEN: ${{ secrets.slack_oauth_token }}
  args:
    - ${{ env.PR_AUTHOR }}
    - ${{ env.REPO }}
    - ${{ env.COMMIT }}
    - ${{ env.MESSAGE }}
    - ${{ env.STATUS }}
    - ${{ env.WORKFLOW }}
    - ${{ env.JOB_NAME }}
    - ${{ secrets.slack_mapping }}
    - ${{ secrets.slack_oauth_token }}
